import fs from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const OUT = path.join(ROOT, 'dist');
const PUBLIC = path.join(OUT, 'public');
const FUNC_LIB = path.join(ROOT, 'cloudfunctions', 'portfolio', 'lib');
const FUNC_OUT = path.join(OUT, 'cloudfunctions', 'portfolio');
const FUNC_OUT_LIB = path.join(FUNC_OUT, 'lib');

const read = (p) => fs.readFileSync(path.join(ROOT, p), 'utf8');
const readJson = (p) => JSON.parse(read(p));

// ---------------------------------------------------------------------------
// 1. Static site for CloudBase static hosting: index.html, style.css, app.js.
fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(PUBLIC, { recursive: true });
for (const file of ['index.html', 'style.css', 'app.js']) {
  fs.copyFileSync(path.join(ROOT, 'src', file), path.join(PUBLIC, file));
}

// 2. Seed images: decode the base64 payloads into /seed/*.jpg static files.
const seedAssets = { ...readJson('src/seed-assets.json'), ...readJson('src/fashion-assets.json') };
const seedDir = path.join(PUBLIC, 'seed');
fs.mkdirSync(seedDir, { recursive: true });
let seedCount = 0;
for (const [key, base64] of Object.entries(seedAssets)) {
  const name = key.replace(/^\/seed\//, '');
  fs.writeFileSync(path.join(seedDir, name), Buffer.from(base64, 'base64'));
  seedCount += 1;
}

// 3. Cloud function data: only the small JSON payloads the worker needs at
//    runtime. Seed image bytes are served by static hosting, not the function.
const data = {
  SEED_DATA: readJson('src/seed.json'),
  FASHION_IMPORT: readJson('src/fashion-import.json'),
  VIDEO_DEFAULTS: readJson('src/video-defaults.json')
};
fs.mkdirSync(FUNC_OUT_LIB, { recursive: true });
fs.writeFileSync(
  path.join(FUNC_OUT, 'data.js'),
  "'use strict';\n// Generated by scripts/build.mjs - do not edit.\nmodule.exports = " + JSON.stringify(data) + ';\n'
);

// 4. Cloud function: worker logic + vendored libs.
fs.copyFileSync(path.join(ROOT, 'src', 'worker.js'), path.join(FUNC_OUT, 'index.js'));
for (const lib of ['cloud.js', 'auth.js', 'store.js', 'http.js']) {
  fs.copyFileSync(path.join(FUNC_LIB, lib), path.join(FUNC_OUT_LIB, lib));
}
fs.copyFileSync(
  path.join(ROOT, 'cloudfunctions', 'portfolio', 'package.json'),
  path.join(FUNC_OUT, 'package.json')
);

console.log(`Built CloudBase bundle: public/ (${seedCount} seed images) + cloudfunctions/portfolio/`);